### ISSUE TITLE
Error: Javascript worklet error only on iOS devices

### ISSUE THREAD

**Issue by clh97** [rodgomesc/vision-camera-code-scanner#102]
Hi all,

Obtaining the following error when trying to use frameProcessor according to documentation.

This error happens when processing any frames only on iOS devices, works correctly on android devices.

```
Error: Javascript worklet error
    at scanBarcodes (native)
    at _f (/Users/user/work/eng-mobile/src/helpers/qrcode.ts (12:43):1:131)
    at _f (native)
    at _f (/Users/user/work/eng-mobile/node_modules/react-native-vision-camera/src/hooks/useFrameProcessor.ts (28:21):1:425)
    at _f (native)
```

Camera screen render:

```typescript
const [frameProcessor, barcodes] = useScanBarcodes([BarcodeFormat.QR_CODE]);
...
return (
          <>
            {cameraDevice != null && (
              <Camera
                ref={camera}
                device={cameraDevice}
                isActive={true}
                style={{ flex: 1 }}
                frameProcessor={frameProcessor}

              />
            )}
            <QrCodeOverlay />
          </>
        );
```

useScanBarcodes hook:
```typescript
import { useState } from 'react';
import { runOnJS } from 'react-native-reanimated';
import { Frame, useFrameProcessor } from 'react-native-vision-camera';
import { Barcode, BarcodeFormat, CodeScannerOptions, scanBarcodes } from 'vision-camera-code-scanner';

export function useScanBarcodes(
  types: BarcodeFormat[],
  options?: CodeScannerOptions,
): [(frame: Frame) => void, Barcode[]] {
  const [barcodes, setBarcodes] = useState<Barcode[]>([]);

  const frameProcessor = useFrameProcessor(frame => {
    'worklet';

    try {
      const detectedBarcodes = scanBarcodes(frame, types, options);

      runOnJS(setBarcodes)(detectedBarcodes);
    } catch (err) {
      console.log(err.message);
    }
  }, []);

  return [frameProcessor, barcodes];
}
```

I'm using an updated mac with M1 pro processor.
RN version: `"react-native": "0.68.3",`
Node version: tested with `v14.20.1` and `v12.22.0`

<img width="537" alt="image" src="https://user-images.githubusercontent.com/32719987/193473411-d69076c4-725e-44bd-91a6-819d6494c0c9.png">

**Comment by alexco2** [comment]
I have the same issue. If I use a self build test-frameprocessor, everything works fine

**Comment by zzz08900** [comment]
[Similiar issue](https://github.com/mrousavy/react-native-vision-camera/issues/1244)

I'm not sure where the problem is. Multiple frame processors are crashing and some still works fine.
Only thing I'm sure of is downgrading to Xcode 13.x gets everything back in order.

**Comment by alexco2** [comment]
this fixed my issue
https://github.com/mrousavy/react-native-vision-camera/issues/1244#issuecomment-1264383644

**Comment by clh97** [comment]
@alexco2 applying this patch also fixes my issue, really seems to be specific to xcode 14.
thanks for the help <3
