### ISSUE TITLE
Error Build

### ISSUE THREAD

**Issue by radenlarko** [rodgomesc/vision-camera-code-scanner#108]
Error buils gradlew assembleRelease

My library versions:
    "react": "18.1.0",
    "react-native": "0.70.4",
    "react-native-reanimated": "^2.10.0",
    "react-native-vision-camera": "^2.14.1",
    "vision-camera-code-scanner": "^0.2.0"

And I've also added this setting:
        VisionCameraCodeScanner_targetSdkVersion = 31
        VisionCameraCodeScanner_compileSdkVersion = 31

The previous few days it was running normally, but today an error occurred during build

Here is the error details:
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':vision-camera-code-scanner:verifyReleaseResources'.
> Could not resolve all task dependencies for configuration ':vision-camera-code-scanner:releaseRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :vision-camera-code-scanner
         project :vision-camera-code-scanner > project :react-native-vision-camera
         project :vision-camera-code-scanner > project :react-native-vision-camera > project :react-native-reanimated
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Read timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

Can anyone help?

**Comment by TarunDas005** [comment]
I am still facing the same issues.

**Comment by lightnate** [comment]
I tried to disconnect the network and build successful.

**Comment by xyylb** [comment]
我也遇到了相同的问题，断网后重新构建成功

**Comment by Zuxelus** [comment]
You have this error because jcenter.bintray.com is down. It is deprecated for almost 2 years. Don't use it in your build.gradle.
https://blog.gradle.org/jcenter-shutdown

**Comment by chromakeeey** [comment]
need to change` jcenter()` -> `mavenCental()` on `node_modules/vision-camera-code-scanner/android/build.gradle: 5 and 52 lines`
that's works for me

**Comment by lfrallon** [comment]
[#35136](https://github.com/facebook/react-native/issues/35136)

**Comment by radenlarko** [comment]
> 
I am using react native 0.70.4 and of course there is no jcenter() in build.gradle

**Comment by radenlarko** [comment]
Turning off internet connection is one solution, but i used @chromakeeey  suggestion and it worked fine
