### ISSUE TITLE
Undefined symbols for architecture x86_64 build error. IOS 

### ISSUE THREAD

**Issue by FutureCake** [rodgomesc/vision-camera-code-scanner#114]
I am unable to build my project after added this package. I get the the following error: 

`Undefined symbols for architecture x86_64 build`

I have a full explanation of the problem on [Stackoverflow](https://stackoverflow.com/questions/74382713/vision-camera-code-scanner-undefined-symbols-for-architecture-x86-64-react-nativ) including with what i have tried without any luck. I hope someone here has ran into the same problem and has found a solution or can point me in the right direction.

**Comment by antstu** [comment]
having the same issue, no luck as of now

**Comment by FutureCake** [comment]
After lots of futile attempts the only solution that worked for me was running it directly on my device as stated in the following react native [link](https://reactnative.dev/docs/running-on-device).  
This fixed the compile issue. 

If anyone has a better solution that still allows me to develop on the simulator please let me know.

**Comment by antstu** [comment]
@FutureCake this worked for me  https://github.com/facebook/react-native/issues/29605 - you need to add arm64 to excluded architectures for both the project and target in xcode

**Comment by FutureCake** [comment]
@antstu I tried this before, but it didnt work... 
Are you working on a M1 mac or intel based mac?

**Comment by antstu** [comment]
@FutureCake I'm on a M1 mac

**Comment by antstu** [comment]
@FutureCake  add this to your Podfile: 
```
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Disable arm64 builds for the simulator
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
```

Then
```
cd ios
rm -rf Pods Podfile.lock
pod install
```

src: https://gist.github.com/badsyntax/72c5c965fcaefe66d049a8c2cdf34198

**Comment by Maorshl** [comment]
After `pod install` add this through xcode to your Pods project
<img width="727" alt="Screen Shot 2022-11-20 at 16 06 39" src="https://user-images.githubusercontent.com/56290456/202906660-0c182b42-fd6a-4a8f-8619-75723f974160.png">

**Comment by CodingByJerez** [comment]
same problem, it does not work on the simulator

**Comment by FutureCake** [comment]
For anyone still experiencing this issue i solved it thanks to the image of @Maorshl. 
In my case setting the excluded Architectures in my `.xcworkspace` file for pods was the issue. Because by default the setting was only targeting `boost` under the **Targets** tab. After changing it to `Pods` under the **Project** tab i managed to build for the simulator. 

I feel incredibly stupid for not realising this after two weeks of pain... 

@CodingByJerez if you also tried the above solution without any luck maybe create a new project and copy the source code over. (i did this approach and with the hep of what i mentioned above i got it all to work)

Hopefully this helps anyone in the future.

**Comment by Diego10x** [comment]
> After `pod install` add this through xcode to your Pods project <img alt="Screen Shot 2022-11-20 at 16 06 39" width="727" src="https://user-images.githubusercontent.com/56290456/202906660-0c182b42-fd6a-4a8f-8619-75723f974160.png">

it worked for me



> For anyone still experiencing this issue i solved it thanks to the image of @Maorshl. In my case setting the excluded Architectures in my `.xcworkspace` file for pods was the issue. Because by default the setting was only targeting `boost` under the **Targets** tab. After changing it to `Pods` under the **Project** tab i managed to build for the simulator.
> 
> I feel incredibly stupid for not realising this after two weeks of pain...
> 
> @CodingByJerez if you also tried the above solution without any luck maybe create a new project and copy the source code over. (i did this approach and with the hep of what i mentioned above i got it all to work)
> 
> Hopefully this helps anyone in the future.

I was also doing the same XD
