### ISSUE TITLE
rename to react-native-vision-camera-code-scanner?

### ISSUE THREAD

**Issue by pke** [rodgomesc/vision-camera-code-scanner#13]
As discussed briefly over at RNVC discussion groups do you consider to rename the project before it lifts off? ;)

`react-native-vision-camera-code-scanner` is long but makes the connection to react-native-vision-camera clear and follows other npm pluggable packages (eslint-plugin-*)

`vision-camera-code-scanner` would probably fine too unless there is a `vision-camera` project in the future.

Maybe it could also directly move under an umbrella orga repo: `@react-native-vision-camera/code-scanner`?

Keep up the good work, saved me a ton of work ;)

**Comment by rodgomesc** [comment]
solved in https://github.com/rodgomesc/vision-camera-code-scanner/pull/26, 

[0.1.6](https://www.npmjs.com/package/vision-camera-code-scanner) is now available on npmjs
