### ISSUE TITLE
Property '_setGlobalConsole' doesn't exist

### ISSUE THREAD

**Issue by niubiletei** [rodgomesc/vision-camera-code-scanner#135]
I meet a problem: **Property '_setGlobalConsole' doesn't exist**
I  also set the babel.config.js:  
    module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'react-native-reanimated/plugin',
      {
        globals: ['__scanCodes'],
      },
    ],
  ],
};  
![f5caea8da0c2728d12f31ff2b6cc79e](https://user-images.githubusercontent.com/107567437/224462338-cb86b047-e209-4822-96e1-3858c831a353.jpg)
Please help me! @rodgomesc

**Comment by niubiletei** [comment]
> I meet a problem: **Property '_setGlobalConsole' doesn't exist** I also set the babel.config.js: module.exports = { presets: ['module:metro-react-native-babel-preset'], plugins: [ [ 'react-native-reanimated/plugin', { globals: ['__scanCodes'], }, ], ], }; ![f5caea8da0c2728d12f31ff2b6cc79e](https://user-images.githubusercontent.com/107567437/224462338-cb86b047-e209-4822-96e1-3858c831a353.jpg) Please help me! @rodgomesc

**Comment by nitin992503** [comment]
@niubiletei were you able to resolve this?

**Comment by niubiletei** [comment]
@nitin992503 This question comes from https://github.com/mrousavy/react-native-vision-camera/issues/1514,you can look this

**Comment by abdymm** [comment]
still having this issue, are you guys able to resolve this?
