### ISSUE TITLE
Not able to import hook (typescript)

### ISSUE THREAD

**Issue by mrados7** [rodgomesc/vision-camera-code-scanner#14]
Lib has not exported neither `useScanBarcodes` `BarcodeFormat `from 'vision-camera-qrcode-scanner'; version 0.1.4. So there is no way to use it actually.

**Comment by chiubaka** [comment]
@harloware Can you elaborate on what you did to get around this? The NPM and Github READMEs look the same to me currently.

**Comment by chiubaka** [comment]
And I don't see `useScanBarcodes` or `BarcodeFormat` exported from `0.1.4`, unless I missed something.

**Comment by chiubaka** [comment]
Ah, ok, for posterity, after installing this directly from Github (`"vision-camera-qrcode-scanner": "rodgomesc/vision-camera-qrcode-scanner"` in `package.json`) I ended up with:
```
import {
  Barcode,
  BarcodeFormat,
  useScanBarcodes,
} from "vision-camera-qrcode-scanner/src";
```
And typing issues are now resolved. The new `useScanBarcodes` hook is the piece that hasn't made it into an NPM release yet.

README on NPM is the `0.1.4` README, and offers a complete example that works without the `useScanBarcodes` hook.

**Comment by TheEhsanSarshar** [comment]
@rodgomesc 
is there anything I can do for you

**Comment by chiubaka** [comment]
Smells to me like @rodgomesc needs to tag a new release and publish to NPM. This repo is relatively new, so I'm guessing that's happening manually right now. Probably not much the rest of us can do in the meantime, since I don't think we can actually publish for him.

But do let us know how we can help @rodgomesc!

**Comment by rodgomesc** [comment]
solved in https://github.com/rodgomesc/vision-camera-code-scanner/pull/26, 

[0.1.6](https://www.npmjs.com/package/vision-camera-code-scanner) is now available on npmjs
