### ISSUE TITLE
 ERROR  ReferenceError: Can't find variable: _setGlobalConsole

### ISSUE THREAD

**Issue by mohitharshan123** [rodgomesc/vision-camera-code-scanner#146]
Error when using  

`    "react-native-reanimated": "^3.1.0",
`

**Comment by IsaacNewtonTingo** [comment]
> Error when using
> 
> ` "react-native-reanimated": "^3.1.0",`

Didi you find solution?

**Comment by mohitharshan123** [comment]
@IsaacNewtonTingo No. I switched to using the expo qr scanner since we can now use expo components in react native after `npx install-expo-modules`

**Comment by hariirawan** [comment]
> install-expo-modules

Thank you for the information, I have been searching for days about this problem and found the answer to your information @mohitharshan123
