### ISSUE TITLE
Can‘t recognize the QR code of Etherscan.

### ISSUE THREAD

**Issue by zitup** [rodgomesc/vision-camera-code-scanner#147]
<img width="998" alt="image" src="https://github.com/rodgomesc/vision-camera-code-scanner/assets/12710516/63fc2ea8-6551-47fe-a9ad-62b08e5d4458">

For example, this QR code cannot be accurately recognized. I suspect it is a problem with the QR code. Is there any solution?

**Comment by amanzrx4** [comment]
Does it recognize any other qr code? could you share your library versions.

**Comment by zitup** [comment]
It is because the dark theme affects the qrcode... I will close this issue
