### ISSUE TITLE
DO NOT USE THIS LIBRARY, THIS DOES NOT WORK AT ALL

### ISSUE THREAD

**Issue by lockieluke** [rodgomesc/vision-camera-code-scanner#158]
This library is unmaintained and it does not work with recent versions of vision-camera

**Comment by samcodeng** [comment]
what other alternatives?

**Comment by lockieluke** [comment]
i don't even know at this point i just made a custom frame processor with react-native-vision-camera

**Comment by samcodeng** [comment]
can you share more info to your solution? @lockieluke

**Comment by abdymm** [comment]
agreed

**Comment by Radiant-F** [comment]
nah it worked for me.
react native 0.74.2
jdk 17
rnvc 2.16.1
pop os 22.04

**Comment by JosephShering** [comment]
@lockieluke Would you be open to creating a repository to share with the open source community? We currently rely on this library, and would love to help you with the code-scanner.

**Comment by rodgomesc** [comment]
im rewriting this lib for from scratch expect some updates soon
