### ISSUE TITLE
Crashes on startup on Xcode 15

### ISSUE THREAD

**Issue by QSuraj** [rodgomesc/vision-camera-code-scanner#161]
The app crashes in xcode 15 on app start up with following error 

`Swift class extensions and categories on Swift classes are not allowed to have +load methods`

![image](https://github.com/rodgomesc/vision-camera-code-scanner/assets/91066452/acc6e107-50df-4d4f-bed5-394d314d8a7b)

**Comment by QSuraj** [comment]
@rodgomesc Any idea why this might be happening?

**Comment by QSuraj** [comment]
https://github.com/mrousavy/react-native-vision-camera/issues/1307#issuecomment-1727199001 This solved the initial crash issue, but the app crashes when I open the camera with following error - 
```
libc++abi: terminating due to uncaught exception of type facebook::jsi::JSError: Exception in HostFunction: <unknown>

Error: Exception in HostFunction: <unknown>
    at _f (native)
```

@rodgomesc Any idea why this might be happening?

**Comment by joren-vos-aca** [comment]
Fix is mentioned here: https://github.com/mrousavy/react-native-vision-camera/issues/1307#issuecomment-1731248952

**Comment by medonja** [comment]
> Fix is mentioned here: [mrousavy/react-native-vision-camera#1307 (comment)](https://github.com/mrousavy/react-native-vision-camera/issues/1307#issuecomment-1731248952)

Does this actually work? I tried changing `@interface objc_name (FrameProcessorPlugin)` to `@interface objc_name (FrameProcessorPlugin)   <FrameProcessorPluginBase>` in `/ios/Pods/Headers/Public/VisionCamera/FrameProcessorPlugin.h `and` /ios/Pods/Headers/Private/VisionCamera/FrameProcessorPlugin.h`, but this did not help. Maybe I am doing something completely wrong?

**Comment by feardarkness** [comment]
@medonja  It works. Maybe some dependency issue?
"react-native": "0.71.13"
"react-native-vision-camera": "2.16.1"
"react-native-reanimated": "3.5.4"
"vision-camera-code-scanner": "0.2.0"

**Comment by santagli-bds** [comment]
> @medonja It works. Maybe some dependency issue? "react-native": "0.71.13" "react-native-vision-camera": "2.16.1" "react-native-reanimated": "3.5.4" "vision-camera-code-scanner": "0.2.0"

You use xcode 15?

**Comment by medonja** [comment]
> > @medonja It works. Maybe some dependency issue? "react-native": "0.71.13" "react-native-vision-camera": "2.16.1" "react-native-reanimated": "3.5.4" "vision-camera-code-scanner": "0.2.0"
> 
> You use xcode 15?

I do.
My dependencies:
"react-native": "0.68.7",
"react-native-vision-camera": "2.16.1",
"react-native-reanimated": "3.5.4",
"vision-camera-code-scanner": "0.2.0"

and this is my adapted

`/ios/Pods/Headers/Private/VisionCamera/FrameProcessorPlugin.h` and
`/ios/Pods/Headers/Public/VisionCamera/FrameProcessorPlugin.h`

![grafik](https://github.com/rodgomesc/vision-camera-code-scanner/assets/9157689/1753a53e-fd04-466a-aa06-e64c9a3ad81d)

**Comment by QSuraj** [comment]
Closing the issue, fix - https://github.com/mrousavy/react-native-vision-camera/issues/1307#issuecomment-1731248952
