### ISSUE TITLE
Can't find variable __scanCodes

### ISSUE THREAD

**Issue by rosen777** [rodgomesc/vision-camera-code-scanner#39]
Hello,

I keep getting a can't find variable scan __scanCodes error having implemented the babel.config.js as in the README.md and having imported the vision-camera code scanner library according to the documentation. The errors log as "TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[8], "vision-camera-code-scanner").useScanBarcodes')". and "Error: Requiring module "node_modules/vision-camera-code-scanner/src/index.ts", which threw an exception: ReferenceError: Can't find variable: __scanCodes ".

Thank you.

**Comment by mhdsoft** [comment]
i got same problem

**Comment by mhdsoft** [comment]
i got same problem. 
but finaly edit babel.config to
module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: [
    [
      "react-native-reanimated/plugin",
      {
        globals: ["__scanCodes"],
      },
    ],
  ],
};

at first in plugins i used one [] but the corected one needs two and after that you have to  rebuild project

**Comment by yachaka** [comment]
I have the same problem yet I did edit `babel.config.js` ?

**Comment by yachaka** [comment]
I had the same problem I forgot to run Pods install

**Comment by rosen777** [comment]
My issue was on Android. Cleaning the cache and restarting my computer seems to have resolved it.

**Comment by Joshfindit** [comment]
Since I'm here, here's the highlighted code for `babel.config.js`:

```javascript
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
  ],
  plugins: [
    [
      'react-native-reanimated/plugin',
      {
        globals: ['__scanCodes'],
      },
    ],
  ],
};
```

(Functionally the same code as @mhdsoft posted)

**Comment by 26903651** [comment]
Same problem on Android. 
yarn cache clean is invalid.
babel.config.js is set correctly.
Android project has been rebuilt.
Can anyone help?

"react-native": "0.68.2"

**Comment by 26903651** [comment]
Same problem on Android. 
yarn cache clean is invalid.
babel.config.js is set correctly.
Android project has been rebuilt.
Can anyone help?

"react-native": "0.68.2"

**Comment by rosen777** [comment]
Have you also tried to restart your computer? I did all the steps you listed and the error was resolved after a restart.

**Comment by 26903651** [comment]
I tried it, but it is not continuous execution, I will try continuous execution again, and then restart directly

**Comment by 26903651** [comment]
I tried it, still doesn't work

**Comment by 26903651** [comment]
I solved with `yarn start --reset-cache`

**Comment by fukemy** [comment]
i did everything suggest but not working, android work but ios failed
