### ISSUE TITLE
Inverted Barcode Support

### ISSUE THREAD

**Issue by rgbdelta** [rodgomesc/vision-camera-code-scanner#42]
I've encountered a use case where I'll need to detect inverted barcodes where the lines are bright and the background is black as well as normal barcodes. Would you be interested in receiving a pull request from me to add support for this?

It could be as simple as providing a flag for `checkInverted` in the API like this.
```typescript
scanBarcodes(frame, [BarcodeFormat.QR_CODE], {checkInverted: true})
```

It would then check for a standard barcode. If nothing is detected it would then extract the underlying Bitmap from the image and invert the pixels before passing the image to the mlkit vision barcode scanner again.

**Comment by rodgomesc** [comment]
of course, that’s  looks awesome
