### ISSUE TITLE
[Inverted barcode detection] When the next release will be published to npm registry?

### ISSUE THREAD

**Issue by lffloyd** [rodgomesc/vision-camera-code-scanner#50]
Hello @rodgomesc, how are you doing?

So, is there any prediction of when the next release will be made on npm registry?
I need to use the inverted barcode detection capabilities brought by #44, but in my use case, is not feasible to point to a github address on ```npm install``` execution.

Anyway, thanks for the great work! 

Relevant discussions are #36, #42, #44

**Comment by rodgomesc** [comment]
v0.2.0 is out 🚀🚀🚀
