### ISSUE TITLE
Requiring module "node_modules/vision-camera-qrcode-scanner/src/index.ts", which threw an exception: TypeError: undefined is not a function, js engine: hermes

### ISSUE THREAD

**Issue by thanhnh-alobridge** [rodgomesc/vision-camera-code-scanner#8]

**Comment by rodgomesc** [comment]
make sure that you followed all installation steps for react-native-reanimated in [installation instructions](https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/installation/)

**Comment by rodgomesc** [comment]
solved in https://github.com/rodgomesc/vision-camera-code-scanner/pull/26, 

[0.1.6](https://www.npmjs.com/package/vision-camera-code-scanner) is now available on npmjs

**Comment by Bamorem** [comment]
this error happen also on the https://www.npmjs.com/package/vision-camera-qrcode-scanner
can you fix the bug also on the QR code scanner ?
