### ISSUE TITLE
vision-camera-code-scanner:verifyReleaseResources

### ISSUE THREAD

**Issue by h-assefi** [rodgomesc/vision-camera-code-scanner#90]
As I want to make a release. after, I run ./gradlew assembleRelease command.
I get the below error

```
A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\pc\.gradle\caches\transforms-3\b5a8e99dac667ebea08e9f9757d3b404\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
```

can anyone help with this ?

**Comment by rvuyyuru1** [comment]
Please mention your issue clearly @h-assefi  so that any one can help

**Comment by h-assefi** [comment]
@rvuyyuru1 Thank you for your reply

I was able to fix this by adding below code to _android/build.gradle_ file.
```
buildscript {
    ext {
           ...
           VisionCameraCodeScanner_compileSdkVersion=31
          }
}
```

Then, run commands in terminal

./gradlew clean
./gradlew assembleRelease

**Comment by ljc2114** [comment]
> VisionCameraCodeScanner_compileSdkVersion=31

This is useful to me
