### ISSUE TITLE
is it possible to make reanimated2 an optional dependency (conflicts with realm)

### ISSUE THREAD

**Issue by uniquejava** [rodgomesc/vision-camera-code-scanner#94]
Hello, 

Thanks for your effort and so we are switching from RNC to RNVC, and switching from react-native-qrcode-scanner to this code-scaner.

But when use this plugin, we met some issue.

Currently we are using [realm](https://github.com/realm/realm-js/) as our app offline solution, it's used everywhere in our app. However the realm sdk conflicts with reanimated v2.

see this issue: https://github.com/realm/realm-js/issues/3837

though the issue is closed, it used a workaround(an earlier beta edition), yet that version has significant performance issue.

see https://github.com/realm/realm-js/issues/4443

so we don't really like to upgrade to an beta and unstable realm version.

my question is can this plugin just like react-native-vision-camera does, make `react-native-reanimated` an optional dependency, so both this plugin and realm sdk can co-exist.

**Comment by whalemare** [comment]
As I know, vision-camera used `reanimated` for worklets and background computation, so - no

**Comment by uniquejava** [comment]
@whalemare Thanks for your reply, yes later I knew that if you want to use the camera frameProcessor you have to include reanimated2, we will just wait for realm to release v11, and seems they already made great progress on this based on the discussion. I will just close this issue.
