### ISSUE TITLE
Double read of QR code

### ISSUE THREAD

**Issue by Productivix** [rodgomesc/vision-camera-code-scanner#97]
just a remark : (not issue)
if you put : 
` {
      checkInverted: true,
    }, 
`
you will read 2 times a QRCode (the normal and the inverted one) , but 1 time a linear barcode

**Comment by tahaipek** [comment]
How did you solve this problem?

**Comment by Productivix** [comment]
hi, 
I replaced 'true' by 'false' or suppress this option. simple

**Comment by tahaipek** [comment]
Hi, 
Ok, thanks for your answer. Although { checkInverted: true }, I thought it deduplicated these 2 records.
